### ISSUE TITLE
Proxmox 8 Support

### ISSUE THREAD

**Issue by zchoate** [ironicbadger/ansible-role-proxmox-nag-removal#21]
First, thanks for putting this together as well your infra repo! It's a great reference when IaCing my home lab.

I just tried installing this role on a new Proxmox 8 box. It looks like Proxmox 8 includes a new source for ceph which also needs to be updated. The *add-no-subscription repo* task fails because the ceph.list (newly added in 8 maybe?) is pointed at the enterprise repo. I manually updated this to `deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription` and the task ran successfully adding the pve-no-subscription repo as expected.

The nag message tweak appears to be broken.

If you like I can try to put together the changes while trying to maintain backwards compatibility and submit a PR.

**Comment by zchoate** [comment]
Disregard the nag message comment...helps if I clear my cache ;-). The tweak still works for Proxmox 8.

**Comment by BeyondEvil** [comment]
Here's what I do to handle the new ceph-quincy package:

```yaml
  tasks:
    - name: Set the "no-subscription" repositories
      ansible.builtin.apt_repository:
        filename: "{{ item.filename }}"
        repo: "deb http://download.proxmox.com/debian/{{ item.repo }} bookworm {{ item.package }}"
        state: present
        update_cache: false
      loop:
        - {filename: pve-no-subscription, repo: pve, package: pve-no-subscription}
        - {filename: ceph, repo: ceph-quincy, package: no-subscription}
      notify: Update APT cache

    - name: Remove the "enterprise" repositories
      ansible.builtin.apt_repository:
        filename: "{{ item.filename }}"
        repo: "deb https://enterprise.proxmox.com/debian/{{ item.repo }} bookworm {{ item.package }}"
        state: absent
        update_cache: false
      loop:
        - {filename: pve-enterprise, repo: pve, package: pve-enterprise}
        - {filename: ceph, repo: ceph-quincy, package: enterprise}
      notify: Update APT cache

  handlers:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true
```
