### ISSUE TITLE
"New" way of removing the nag screen.

### ISSUE THREAD

**Issue by BeyondEvil** [ironicbadger/ansible-role-proxmox-nag-removal#24]
Per [johnscs.com](https://johnscs.com/remove-proxmox51-subscription-notice/):

```yaml
  tasks:
    - name: Silence the Proxmox subscription nag
      ansible.builtin.blockinfile:
        path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
        insertafter: 'checked_command: function\(orig_cmd\) {$'
        block: |
          {% filter indent(width=8, first=true) %}
          orig_cmd();
          return;
          {% endfilter %}
        marker: "\t// {mark} Ansible managed block"
        backup: true
      notify: Restart Proxmox

  handlers:
    - name: Restart Proxmox
      ansible.builtin.systemd:
        name: pveproxy
        state: restarted
```

Tested on 8.2.2
